package com.example.demo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    public TaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTopicIsNull() {
            addCriterion("topic is null");
            return (Criteria) this;
        }

        public Criteria andTopicIsNotNull() {
            addCriterion("topic is not null");
            return (Criteria) this;
        }

        public Criteria andTopicEqualTo(String value) {
            addCriterion("topic =", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicNotEqualTo(String value) {
            addCriterion("topic <>", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicGreaterThan(String value) {
            addCriterion("topic >", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicGreaterThanOrEqualTo(String value) {
            addCriterion("topic >=", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicLessThan(String value) {
            addCriterion("topic <", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicLessThanOrEqualTo(String value) {
            addCriterion("topic <=", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicLike(String value) {
            addCriterion("topic like", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicNotLike(String value) {
            addCriterion("topic not like", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicIn(List<String> values) {
            addCriterion("topic in", values, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicNotIn(List<String> values) {
            addCriterion("topic not in", values, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicBetween(String value1, String value2) {
            addCriterion("topic between", value1, value2, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicNotBetween(String value1, String value2) {
            addCriterion("topic not between", value1, value2, "topic");
            return (Criteria) this;
        }

        public Criteria andCollegeIdIsNull() {
            addCriterion("college_id is null");
            return (Criteria) this;
        }

        public Criteria andCollegeIdIsNotNull() {
            addCriterion("college_id is not null");
            return (Criteria) this;
        }

        public Criteria andCollegeIdEqualTo(String value) {
            addCriterion("college_id =", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdNotEqualTo(String value) {
            addCriterion("college_id <>", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdGreaterThan(String value) {
            addCriterion("college_id >", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdGreaterThanOrEqualTo(String value) {
            addCriterion("college_id >=", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdLessThan(String value) {
            addCriterion("college_id <", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdLessThanOrEqualTo(String value) {
            addCriterion("college_id <=", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdLike(String value) {
            addCriterion("college_id like", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdNotLike(String value) {
            addCriterion("college_id not like", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdIn(List<String> values) {
            addCriterion("college_id in", values, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdNotIn(List<String> values) {
            addCriterion("college_id not in", values, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdBetween(String value1, String value2) {
            addCriterion("college_id between", value1, value2, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdNotBetween(String value1, String value2) {
            addCriterion("college_id not between", value1, value2, "collegeId");
            return (Criteria) this;
        }

        public Criteria andMajorIdIsNull() {
            addCriterion("major_id is null");
            return (Criteria) this;
        }

        public Criteria andMajorIdIsNotNull() {
            addCriterion("major_id is not null");
            return (Criteria) this;
        }

        public Criteria andMajorIdEqualTo(String value) {
            addCriterion("major_id =", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotEqualTo(String value) {
            addCriterion("major_id <>", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdGreaterThan(String value) {
            addCriterion("major_id >", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdGreaterThanOrEqualTo(String value) {
            addCriterion("major_id >=", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdLessThan(String value) {
            addCriterion("major_id <", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdLessThanOrEqualTo(String value) {
            addCriterion("major_id <=", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdLike(String value) {
            addCriterion("major_id like", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotLike(String value) {
            addCriterion("major_id not like", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdIn(List<String> values) {
            addCriterion("major_id in", values, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotIn(List<String> values) {
            addCriterion("major_id not in", values, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdBetween(String value1, String value2) {
            addCriterion("major_id between", value1, value2, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotBetween(String value1, String value2) {
            addCriterion("major_id not between", value1, value2, "majorId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPatternIsNull() {
            addCriterion("pattern is null");
            return (Criteria) this;
        }

        public Criteria andPatternIsNotNull() {
            addCriterion("pattern is not null");
            return (Criteria) this;
        }

        public Criteria andPatternEqualTo(String value) {
            addCriterion("pattern =", value, "pattern");
            return (Criteria) this;
        }

        public Criteria andPatternNotEqualTo(String value) {
            addCriterion("pattern <>", value, "pattern");
            return (Criteria) this;
        }

        public Criteria andPatternGreaterThan(String value) {
            addCriterion("pattern >", value, "pattern");
            return (Criteria) this;
        }

        public Criteria andPatternGreaterThanOrEqualTo(String value) {
            addCriterion("pattern >=", value, "pattern");
            return (Criteria) this;
        }

        public Criteria andPatternLessThan(String value) {
            addCriterion("pattern <", value, "pattern");
            return (Criteria) this;
        }

        public Criteria andPatternLessThanOrEqualTo(String value) {
            addCriterion("pattern <=", value, "pattern");
            return (Criteria) this;
        }

        public Criteria andPatternLike(String value) {
            addCriterion("pattern like", value, "pattern");
            return (Criteria) this;
        }

        public Criteria andPatternNotLike(String value) {
            addCriterion("pattern not like", value, "pattern");
            return (Criteria) this;
        }

        public Criteria andPatternIn(List<String> values) {
            addCriterion("pattern in", values, "pattern");
            return (Criteria) this;
        }

        public Criteria andPatternNotIn(List<String> values) {
            addCriterion("pattern not in", values, "pattern");
            return (Criteria) this;
        }

        public Criteria andPatternBetween(String value1, String value2) {
            addCriterion("pattern between", value1, value2, "pattern");
            return (Criteria) this;
        }

        public Criteria andPatternNotBetween(String value1, String value2) {
            addCriterion("pattern not between", value1, value2, "pattern");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidIsNull() {
            addCriterion("canBeChosencollegeid is null");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidIsNotNull() {
            addCriterion("canBeChosencollegeid is not null");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidEqualTo(String value) {
            addCriterion("canBeChosencollegeid =", value, "canbechosencollegeid");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidNotEqualTo(String value) {
            addCriterion("canBeChosencollegeid <>", value, "canbechosencollegeid");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidGreaterThan(String value) {
            addCriterion("canBeChosencollegeid >", value, "canbechosencollegeid");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidGreaterThanOrEqualTo(String value) {
            addCriterion("canBeChosencollegeid >=", value, "canbechosencollegeid");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidLessThan(String value) {
            addCriterion("canBeChosencollegeid <", value, "canbechosencollegeid");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidLessThanOrEqualTo(String value) {
            addCriterion("canBeChosencollegeid <=", value, "canbechosencollegeid");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidLike(String value) {
            addCriterion("canBeChosencollegeid like", value, "canbechosencollegeid");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidNotLike(String value) {
            addCriterion("canBeChosencollegeid not like", value, "canbechosencollegeid");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidIn(List<String> values) {
            addCriterion("canBeChosencollegeid in", values, "canbechosencollegeid");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidNotIn(List<String> values) {
            addCriterion("canBeChosencollegeid not in", values, "canbechosencollegeid");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidBetween(String value1, String value2) {
            addCriterion("canBeChosencollegeid between", value1, value2, "canbechosencollegeid");
            return (Criteria) this;
        }

        public Criteria andCanbechosencollegeidNotBetween(String value1, String value2) {
            addCriterion("canBeChosencollegeid not between", value1, value2, "canbechosencollegeid");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionIsNull() {
            addCriterion("research_direction is null");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionIsNotNull() {
            addCriterion("research_direction is not null");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionEqualTo(String value) {
            addCriterion("research_direction =", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionNotEqualTo(String value) {
            addCriterion("research_direction <>", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionGreaterThan(String value) {
            addCriterion("research_direction >", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("research_direction >=", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionLessThan(String value) {
            addCriterion("research_direction <", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionLessThanOrEqualTo(String value) {
            addCriterion("research_direction <=", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionLike(String value) {
            addCriterion("research_direction like", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionNotLike(String value) {
            addCriterion("research_direction not like", value, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionIn(List<String> values) {
            addCriterion("research_direction in", values, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionNotIn(List<String> values) {
            addCriterion("research_direction not in", values, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionBetween(String value1, String value2) {
            addCriterion("research_direction between", value1, value2, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andResearchDirectionNotBetween(String value1, String value2) {
            addCriterion("research_direction not between", value1, value2, "researchDirection");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionIsNull() {
            addCriterion("brief_introduction is null");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionIsNotNull() {
            addCriterion("brief_introduction is not null");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionEqualTo(String value) {
            addCriterion("brief_introduction =", value, "briefIntroduction");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionNotEqualTo(String value) {
            addCriterion("brief_introduction <>", value, "briefIntroduction");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionGreaterThan(String value) {
            addCriterion("brief_introduction >", value, "briefIntroduction");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("brief_introduction >=", value, "briefIntroduction");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionLessThan(String value) {
            addCriterion("brief_introduction <", value, "briefIntroduction");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionLessThanOrEqualTo(String value) {
            addCriterion("brief_introduction <=", value, "briefIntroduction");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionLike(String value) {
            addCriterion("brief_introduction like", value, "briefIntroduction");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionNotLike(String value) {
            addCriterion("brief_introduction not like", value, "briefIntroduction");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionIn(List<String> values) {
            addCriterion("brief_introduction in", values, "briefIntroduction");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionNotIn(List<String> values) {
            addCriterion("brief_introduction not in", values, "briefIntroduction");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionBetween(String value1, String value2) {
            addCriterion("brief_introduction between", value1, value2, "briefIntroduction");
            return (Criteria) this;
        }

        public Criteria andBriefIntroductionNotBetween(String value1, String value2) {
            addCriterion("brief_introduction not between", value1, value2, "briefIntroduction");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsIsNull() {
            addCriterion("basic_requirements is null");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsIsNotNull() {
            addCriterion("basic_requirements is not null");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsEqualTo(String value) {
            addCriterion("basic_requirements =", value, "basicRequirements");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsNotEqualTo(String value) {
            addCriterion("basic_requirements <>", value, "basicRequirements");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsGreaterThan(String value) {
            addCriterion("basic_requirements >", value, "basicRequirements");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsGreaterThanOrEqualTo(String value) {
            addCriterion("basic_requirements >=", value, "basicRequirements");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsLessThan(String value) {
            addCriterion("basic_requirements <", value, "basicRequirements");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsLessThanOrEqualTo(String value) {
            addCriterion("basic_requirements <=", value, "basicRequirements");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsLike(String value) {
            addCriterion("basic_requirements like", value, "basicRequirements");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsNotLike(String value) {
            addCriterion("basic_requirements not like", value, "basicRequirements");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsIn(List<String> values) {
            addCriterion("basic_requirements in", values, "basicRequirements");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsNotIn(List<String> values) {
            addCriterion("basic_requirements not in", values, "basicRequirements");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsBetween(String value1, String value2) {
            addCriterion("basic_requirements between", value1, value2, "basicRequirements");
            return (Criteria) this;
        }

        public Criteria andBasicRequirementsNotBetween(String value1, String value2) {
            addCriterion("basic_requirements not between", value1, value2, "basicRequirements");
            return (Criteria) this;
        }

        public Criteria andReferenceDataIsNull() {
            addCriterion("reference_data is null");
            return (Criteria) this;
        }

        public Criteria andReferenceDataIsNotNull() {
            addCriterion("reference_data is not null");
            return (Criteria) this;
        }

        public Criteria andReferenceDataEqualTo(String value) {
            addCriterion("reference_data =", value, "referenceData");
            return (Criteria) this;
        }

        public Criteria andReferenceDataNotEqualTo(String value) {
            addCriterion("reference_data <>", value, "referenceData");
            return (Criteria) this;
        }

        public Criteria andReferenceDataGreaterThan(String value) {
            addCriterion("reference_data >", value, "referenceData");
            return (Criteria) this;
        }

        public Criteria andReferenceDataGreaterThanOrEqualTo(String value) {
            addCriterion("reference_data >=", value, "referenceData");
            return (Criteria) this;
        }

        public Criteria andReferenceDataLessThan(String value) {
            addCriterion("reference_data <", value, "referenceData");
            return (Criteria) this;
        }

        public Criteria andReferenceDataLessThanOrEqualTo(String value) {
            addCriterion("reference_data <=", value, "referenceData");
            return (Criteria) this;
        }

        public Criteria andReferenceDataLike(String value) {
            addCriterion("reference_data like", value, "referenceData");
            return (Criteria) this;
        }

        public Criteria andReferenceDataNotLike(String value) {
            addCriterion("reference_data not like", value, "referenceData");
            return (Criteria) this;
        }

        public Criteria andReferenceDataIn(List<String> values) {
            addCriterion("reference_data in", values, "referenceData");
            return (Criteria) this;
        }

        public Criteria andReferenceDataNotIn(List<String> values) {
            addCriterion("reference_data not in", values, "referenceData");
            return (Criteria) this;
        }

        public Criteria andReferenceDataBetween(String value1, String value2) {
            addCriterion("reference_data between", value1, value2, "referenceData");
            return (Criteria) this;
        }

        public Criteria andReferenceDataNotBetween(String value1, String value2) {
            addCriterion("reference_data not between", value1, value2, "referenceData");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIsNull() {
            addCriterion("teacher_id is null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIsNotNull() {
            addCriterion("teacher_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdEqualTo(String value) {
            addCriterion("teacher_id =", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotEqualTo(String value) {
            addCriterion("teacher_id <>", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdGreaterThan(String value) {
            addCriterion("teacher_id >", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_id >=", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLessThan(String value) {
            addCriterion("teacher_id <", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLessThanOrEqualTo(String value) {
            addCriterion("teacher_id <=", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLike(String value) {
            addCriterion("teacher_id like", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotLike(String value) {
            addCriterion("teacher_id not like", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIn(List<String> values) {
            addCriterion("teacher_id in", values, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotIn(List<String> values) {
            addCriterion("teacher_id not in", values, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdBetween(String value1, String value2) {
            addCriterion("teacher_id between", value1, value2, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotBetween(String value1, String value2) {
            addCriterion("teacher_id not between", value1, value2, "teacherId");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(String value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(String value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(String value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(String value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(String value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(String value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLike(String value) {
            addCriterion("audit_status like", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotLike(String value) {
            addCriterion("audit_status not like", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<String> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<String> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(String value1, String value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(String value1, String value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(String value) {
            addCriterion("grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(String value) {
            addCriterion("grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(String value) {
            addCriterion("grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(String value) {
            addCriterion("grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(String value) {
            addCriterion("grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(String value) {
            addCriterion("grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLike(String value) {
            addCriterion("grade like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotLike(String value) {
            addCriterion("grade not like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<String> values) {
            addCriterion("grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<String> values) {
            addCriterion("grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(String value1, String value2) {
            addCriterion("grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(String value1, String value2) {
            addCriterion("grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdIsNull() {
            addCriterion("assignmentbook_id is null");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdIsNotNull() {
            addCriterion("assignmentbook_id is not null");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdEqualTo(String value) {
            addCriterion("assignmentbook_id =", value, "assignmentbookId");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdNotEqualTo(String value) {
            addCriterion("assignmentbook_id <>", value, "assignmentbookId");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdGreaterThan(String value) {
            addCriterion("assignmentbook_id >", value, "assignmentbookId");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdGreaterThanOrEqualTo(String value) {
            addCriterion("assignmentbook_id >=", value, "assignmentbookId");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdLessThan(String value) {
            addCriterion("assignmentbook_id <", value, "assignmentbookId");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdLessThanOrEqualTo(String value) {
            addCriterion("assignmentbook_id <=", value, "assignmentbookId");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdLike(String value) {
            addCriterion("assignmentbook_id like", value, "assignmentbookId");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdNotLike(String value) {
            addCriterion("assignmentbook_id not like", value, "assignmentbookId");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdIn(List<String> values) {
            addCriterion("assignmentbook_id in", values, "assignmentbookId");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdNotIn(List<String> values) {
            addCriterion("assignmentbook_id not in", values, "assignmentbookId");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdBetween(String value1, String value2) {
            addCriterion("assignmentbook_id between", value1, value2, "assignmentbookId");
            return (Criteria) this;
        }

        public Criteria andAssignmentbookIdNotBetween(String value1, String value2) {
            addCriterion("assignmentbook_id not between", value1, value2, "assignmentbookId");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressIsNull() {
            addCriterion("material_address is null");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressIsNotNull() {
            addCriterion("material_address is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressEqualTo(String value) {
            addCriterion("material_address =", value, "materialAddress");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressNotEqualTo(String value) {
            addCriterion("material_address <>", value, "materialAddress");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressGreaterThan(String value) {
            addCriterion("material_address >", value, "materialAddress");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressGreaterThanOrEqualTo(String value) {
            addCriterion("material_address >=", value, "materialAddress");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressLessThan(String value) {
            addCriterion("material_address <", value, "materialAddress");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressLessThanOrEqualTo(String value) {
            addCriterion("material_address <=", value, "materialAddress");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressLike(String value) {
            addCriterion("material_address like", value, "materialAddress");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressNotLike(String value) {
            addCriterion("material_address not like", value, "materialAddress");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressIn(List<String> values) {
            addCriterion("material_address in", values, "materialAddress");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressNotIn(List<String> values) {
            addCriterion("material_address not in", values, "materialAddress");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressBetween(String value1, String value2) {
            addCriterion("material_address between", value1, value2, "materialAddress");
            return (Criteria) this;
        }

        public Criteria andMaterialAddressNotBetween(String value1, String value2) {
            addCriterion("material_address not between", value1, value2, "materialAddress");
            return (Criteria) this;
        }

        public Criteria andMaterialNameIsNull() {
            addCriterion("material_name is null");
            return (Criteria) this;
        }

        public Criteria andMaterialNameIsNotNull() {
            addCriterion("material_name is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialNameEqualTo(String value) {
            addCriterion("material_name =", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotEqualTo(String value) {
            addCriterion("material_name <>", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameGreaterThan(String value) {
            addCriterion("material_name >", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameGreaterThanOrEqualTo(String value) {
            addCriterion("material_name >=", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameLessThan(String value) {
            addCriterion("material_name <", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameLessThanOrEqualTo(String value) {
            addCriterion("material_name <=", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameLike(String value) {
            addCriterion("material_name like", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotLike(String value) {
            addCriterion("material_name not like", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameIn(List<String> values) {
            addCriterion("material_name in", values, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotIn(List<String> values) {
            addCriterion("material_name not in", values, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameBetween(String value1, String value2) {
            addCriterion("material_name between", value1, value2, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotBetween(String value1, String value2) {
            addCriterion("material_name not between", value1, value2, "materialName");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidIsNull() {
            addCriterion("final_paperid is null");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidIsNotNull() {
            addCriterion("final_paperid is not null");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidEqualTo(String value) {
            addCriterion("final_paperid =", value, "finalPaperid");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidNotEqualTo(String value) {
            addCriterion("final_paperid <>", value, "finalPaperid");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidGreaterThan(String value) {
            addCriterion("final_paperid >", value, "finalPaperid");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidGreaterThanOrEqualTo(String value) {
            addCriterion("final_paperid >=", value, "finalPaperid");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidLessThan(String value) {
            addCriterion("final_paperid <", value, "finalPaperid");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidLessThanOrEqualTo(String value) {
            addCriterion("final_paperid <=", value, "finalPaperid");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidLike(String value) {
            addCriterion("final_paperid like", value, "finalPaperid");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidNotLike(String value) {
            addCriterion("final_paperid not like", value, "finalPaperid");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidIn(List<String> values) {
            addCriterion("final_paperid in", values, "finalPaperid");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidNotIn(List<String> values) {
            addCriterion("final_paperid not in", values, "finalPaperid");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidBetween(String value1, String value2) {
            addCriterion("final_paperid between", value1, value2, "finalPaperid");
            return (Criteria) this;
        }

        public Criteria andFinalPaperidNotBetween(String value1, String value2) {
            addCriterion("final_paperid not between", value1, value2, "finalPaperid");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(String value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(String value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(String value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(String value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(String value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(String value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLike(String value) {
            addCriterion("score like", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotLike(String value) {
            addCriterion("score not like", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<String> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<String> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(String value1, String value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(String value1, String value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherIsNull() {
            addCriterion("assess_teacher is null");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherIsNotNull() {
            addCriterion("assess_teacher is not null");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherEqualTo(String value) {
            addCriterion("assess_teacher =", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherNotEqualTo(String value) {
            addCriterion("assess_teacher <>", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherGreaterThan(String value) {
            addCriterion("assess_teacher >", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherGreaterThanOrEqualTo(String value) {
            addCriterion("assess_teacher >=", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherLessThan(String value) {
            addCriterion("assess_teacher <", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherLessThanOrEqualTo(String value) {
            addCriterion("assess_teacher <=", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherLike(String value) {
            addCriterion("assess_teacher like", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherNotLike(String value) {
            addCriterion("assess_teacher not like", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherIn(List<String> values) {
            addCriterion("assess_teacher in", values, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherNotIn(List<String> values) {
            addCriterion("assess_teacher not in", values, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherBetween(String value1, String value2) {
            addCriterion("assess_teacher between", value1, value2, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherNotBetween(String value1, String value2) {
            addCriterion("assess_teacher not between", value1, value2, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessScoreIsNull() {
            addCriterion("assess_score is null");
            return (Criteria) this;
        }

        public Criteria andAssessScoreIsNotNull() {
            addCriterion("assess_score is not null");
            return (Criteria) this;
        }

        public Criteria andAssessScoreEqualTo(String value) {
            addCriterion("assess_score =", value, "assessScore");
            return (Criteria) this;
        }

        public Criteria andAssessScoreNotEqualTo(String value) {
            addCriterion("assess_score <>", value, "assessScore");
            return (Criteria) this;
        }

        public Criteria andAssessScoreGreaterThan(String value) {
            addCriterion("assess_score >", value, "assessScore");
            return (Criteria) this;
        }

        public Criteria andAssessScoreGreaterThanOrEqualTo(String value) {
            addCriterion("assess_score >=", value, "assessScore");
            return (Criteria) this;
        }

        public Criteria andAssessScoreLessThan(String value) {
            addCriterion("assess_score <", value, "assessScore");
            return (Criteria) this;
        }

        public Criteria andAssessScoreLessThanOrEqualTo(String value) {
            addCriterion("assess_score <=", value, "assessScore");
            return (Criteria) this;
        }

        public Criteria andAssessScoreLike(String value) {
            addCriterion("assess_score like", value, "assessScore");
            return (Criteria) this;
        }

        public Criteria andAssessScoreNotLike(String value) {
            addCriterion("assess_score not like", value, "assessScore");
            return (Criteria) this;
        }

        public Criteria andAssessScoreIn(List<String> values) {
            addCriterion("assess_score in", values, "assessScore");
            return (Criteria) this;
        }

        public Criteria andAssessScoreNotIn(List<String> values) {
            addCriterion("assess_score not in", values, "assessScore");
            return (Criteria) this;
        }

        public Criteria andAssessScoreBetween(String value1, String value2) {
            addCriterion("assess_score between", value1, value2, "assessScore");
            return (Criteria) this;
        }

        public Criteria andAssessScoreNotBetween(String value1, String value2) {
            addCriterion("assess_score not between", value1, value2, "assessScore");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(String value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(String value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(String value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(String value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(String value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(String value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLike(String value) {
            addCriterion("del_flag like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotLike(String value) {
            addCriterion("del_flag not like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<String> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<String> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(String value1, String value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(String value1, String value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}