package com.example.demo.dao;

import com.example.demo.entity.AssignmentBook;
import com.example.demo.entity.AssignmentBookExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
public interface AssignmentBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int countByExample(AssignmentBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int deleteByExample(AssignmentBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int insert(AssignmentBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int insertSelective(AssignmentBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    List<AssignmentBook> selectByExample(AssignmentBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    AssignmentBook selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssignmentBook record, @Param("example") AssignmentBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssignmentBook record, @Param("example") AssignmentBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssignmentBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assignment_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssignmentBook record);

    AssignmentBook getAssignmentBookById(String assignmentbookid);

    int insertassignmentBook(AssignmentBook assignmentBook);

    void updateAssignmentBook(AssignmentBook assignmentBook);

    List<AssignmentBook> getAssignmentBookByUser(@Param("userId")String userId);

    List<AssignmentBook> getAssignmentBookListById(String assignmentbookid);
}