package com.example.demo.dao;

import com.example.demo.entity.Office;
import com.example.demo.entity.OfficeExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
public interface OfficeMapper<T> {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int countByExample(OfficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int deleteByExample(OfficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int insert(Office record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int insertSelective(Office record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    List<Office> selectByExample(OfficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    Office selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Office record, @Param("example") OfficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Office record, @Param("example") OfficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Office record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Office record);

    List<Office> findAllOffice();

    Office get(String id);

    List<Office> get1(String id);


    List<Office> getCollegeByUserIdAndGradeId(String userid, String gradeid);

    List<Office> getMajorByUserIdAndGradeIdAndCollegeid(String userid, String gradeid, String collegeid);

    List<Office> getMajorByUserIdAndGradeIdAndCollegeidAndMajorId(String userid, String gradeid, String collegeid, String majorid);

    List<Office> getUserBymajorIdAndIdentitys(@Param("majorId") String majorId, @Param("identitys") String identitys,@Param("usergrade") String usergrade);

    String getOfficeCnNameById(String Id);

    List<Office> get2(String id);
}